name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  

      - name: Install PWABuilder CLI
        run: npm install -g @pwabuilder/cli

      - name: Build Android APK
        run: pwabuilder build android --path . --packageId MY.CALCULATOR --name CALCULATOR

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CALCULATOR-APK
          path: android/app/build/outputs/apk/debug/*.apk
